version: '2.2'
services:
  drawio:
    build:
      context: .
      dockerfile: Dockerfile
    image: drawiowebdav:v1
    container_name: drawiowebdav
    ports:
      - 3000:3000
    networks:
      - drawio
    links:
      - minio
      - drawioservice
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /data/minio:/data
    ports:
      - 9000:9000
    networks:
      - drawio
  drawioservice:
    image: jgraph/drawio
    container_name: drawioservice
    volumes:
      - /data/drawioservice:/data
    ports:
      - 8090:8080
    networks:
      - drawio

networks:
  drawio:
    driver: bridge