version: '2.2'
services:
  drawio:
    image: drawiowebdav:v1
    container_name: drawiowebdav
    ports:
      - 3000:3000
    networks:
      - drawio
    links:
      - minio
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - /data/minio:/data
    ports:
      - 9000:9000
    networks:
      - drawio


networks:
  drawio:
    driver: bridge